import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Grid from "@/components/layout/grid";
import ClientProvider from "@/provider/client-provider";
import Nav from "@/components/layout/nav";
import { Toaster } from "@/components/ui/sonner";
import { db } from "@/db/db";
import { sql } from "drizzle-orm";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  try {
    // 간단한 쿼리 실행 (현재 DB 시간 가져오기)
    const result = await db.execute(sql`SELECT NOW() as now`);
    console.log(result[0].now);
  } catch (error) {
    console.error(error);
  }

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientProvider>
          <Nav />
          <Grid className="mt-6">{children}</Grid> <Toaster />
        </ClientProvider>
      </body>
    </html>
  );
}
