export const DUMMY = [
  {
    id: 582,
    content: "잘보고가요~~\n",
    user_icon: "person_4",
    createAt: "2024-12-18T15:53:51.000Z",
    author_type: "guest",
    guest_nickname: "주황버섯",
    guest_id: 31,
    admin_email: null,
    admin_nickname: null,
    author_role: null,
    parent_id: 581,
  },
  {
    id: 581,
    content: "잘보고가요~~\n",
    user_icon: "person_4",
    createAt: "2024-12-18T15:53:51.000Z",
    author_type: "guest",
    guest_nickname: "주황버섯",
    guest_id: 31,
    admin_email: null,
    admin_nickname: null,
    author_role: null,
    parent_id: null,
  },
  {
    id: 564,
    content: "@화이팅\n방문감사합니다! 추가 프로젝트하며 준비 중 입니다!",
    user_icon: "adminPicture",
    createAt: "2024-07-26T12:13:54.000Z",
    author_type: "admin",
    guest_nickname: null,
    guest_id: null,
    admin_email: "squirrel309@naver.com",
    admin_nickname: "박현민",
    author_role: "super",
    parent_id: null,
  },
];
